# 数据源服务 - 统一领域模型（OpenAPI 3.0 Components）
# 每种数据类型为交付给外部调用方的「标准结果」，与具体数据源解耦

openapi: 3.0.3
info:
  title: Data Service Domain Models
  version: 1.0.0
  description: 统一领域模型规范，供 API 响应与契约使用

components:
  schemas:

    # ---------- 通用 API 响应 ----------
    ApiResponse:
      type: object
      required: [code, message]
      description: 所有 API 的统一响应外壳
      properties:
        code:
          type: integer
          description: 业务/HTTP 状态码，200 为成功
          example: 200
        message:
          type: string
          description: 简短描述
          example: success
        data:
          description: 成功时承载业务数据，失败时为 null
          nullable: true

    # ---------- 股票元信息（标准结果） ----------
    Stock:
      type: object
      required: [ticker, name, data_source]
      description: 统一股票元信息模型，所有 Provider 输出必须映射为此结构
      properties:
        ticker:
          type: string
          description: 股票代码，大写/统一格式
          example: "000001"
        name:
          type: string
          description: 股票名称
          example: "平安银行"
        market:
          type: string
          nullable: true
          description: 市场代码（SSE/SZSE/NASDAQ 等）
        market_type:
          type: string
          nullable: true
          description: 市场类型（A股/港股/美股等）
        sector:
          type: string
          nullable: true
          description: 行业板块
        industry:
          type: string
          nullable: true
          description: 细分行业
        currency:
          type: string
          nullable: true
          description: 货币（CNY/USD 等）
        exchange:
          type: string
          nullable: true
          description: 交易所代码
        country:
          type: string
          nullable: true
          description: 国家/地区
        market_cap:
          type: number
          nullable: true
          description: 市值
        pe_ratio:
          type: number
          nullable: true
          description: 市盈率
        pb_ratio:
          type: number
          nullable: true
          description: 市净率
        dividend_yield:
          type: number
          nullable: true
          description: 股息率
        listing_date:
          type: string
          format: date-time
          nullable: true
          description: 上市日期（ISO 8601）
        data_source:
          type: string
          description: 数据来源标识（如 akshare、yfinance）

    # ---------- 单条 K 线（标准结果） ----------
    Kline:
      type: object
      required: [date, open, high, low, close, volume]
      description: 单条 K 线，历史 K 线 API 返回的数组元素类型
      properties:
        date:
          type: string
          format: date
          description: 日期 YYYY-MM-DD
        timestamp:
          type: string
          format: date-time
          nullable: true
          description: 时间戳（分钟线等可用）
        open:
          type: number
          description: 开盘价
        high:
          type: number
          description: 最高价
        low:
          type: number
          description: 最低价
        close:
          type: number
          description: 收盘价
        volume:
          type: number
          description: 成交量
        amount:
          type: number
          nullable: true
          description: 成交额
        adj_close:
          type: number
          nullable: true
          description: 复权收盘价
        data_source:
          type: string
          nullable: true
          description: 数据来源标识

    # ---------- 批量股票响应 data 结构 ----------
    StockBatchData:
      type: object
      additionalProperties:
        oneOf:
          - $ref: "#/components/schemas/Stock"
          - type: "null"
      description: key 为 ticker，value 为 Stock 或 null

    # ---------- 股票列表响应 data 结构 ----------
    StockListData:
      type: object
      required: [tickers, market]
      properties:
        tickers:
          type: array
          items:
            type: string
          description: 股票代码列表
        market:
          type: string
          description: 市场
        data_source:
          type: string
          description: 实际提供数据的 Provider 名称

    # ---------- 历史 K 线响应 data 结构 ----------
    KlineResponseData:
      type: object
      required: [ticker, period, data]
      properties:
        ticker:
          type: string
        period:
          type: string
          enum: [1m, 5m, 15m, 30m, 60m, 1d, 1w, 1M]
        data:
          type: array
          items:
            $ref: "#/components/schemas/Kline"
        data_source:
          type: string
          description: 实际提供数据的 Provider 名称

    # ---------- 能力查询 - 单个 Provider 信息 ----------
    ProviderInfo:
      type: object
      required: [name, supported_markets, priority]
      properties:
        name:
          type: string
          description: 数据源唯一标识
        supported_markets:
          type: array
          items:
            type: string
          description: 支持的市场列表
        priority:
          type: integer
          description: 优先级，数字越小越高
        features:
          type: array
          items:
            type: string
            enum: [stock_info, stock_list, kline]
          description: 该 Provider 支持的能力列表
        available:
          type: boolean
          nullable: true
          description: 当前是否可用（可选）

    # ---------- 能力查询响应 data 结构 ----------
    CapabilityResponseData:
      type: object
      required: [total_providers, providers]
      properties:
        total_providers:
          type: integer
          description: 已注册 Provider 数量
        providers:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/ProviderInfo"
          description: 按 name 索引的 Provider 信息
        market_coverage:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
          description: 市场 -> 数据源名称列表（按优先级）
        feature_coverage:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
          description: 能力 -> 支持该能力的数据源名称列表
